db/seeds.rb

Creacion de seeds

---

app/controllers/lectures_controller.rb
app/controllers/syllabuses_modules_controller.rb
app/views/lectures/create.html.erb
app/views/lectures/destroy.html.erb
app/views/lectures/update.html.erb
app/views/syllabuses_modules/create.html.erb
app/views/syllabuses_modules/destroy.html.erb
app/views/syllabuses_modules/update.html.erb
config/routes.rb

Ya hice los controllers de modules y lectures e hice unas correcciones en las rutas

Carla controllers views

---

app/controllers/comments_controller.rb
app/controllers/libraries_controller.rb
app/views/comments/create.html.erb
app/views/comments/destroy.html.erb
app/views/comments/update.html.erb
app/views/libraries/create.html.erb
app/views/libraries/index.html.erb
app/views/libraries/new.html.erb
config/routes.rb
db/seeds.rb

Listo. Controlador de libraries y se creo la ruta de libraries. :)

Sandy controlador libraries

---

app/controllers/syllabuses_controller.rb
app/views/syllabuses/create.html.erb
app/views/syllabuses/destroy.html.erb
app/views/syllabuses/edit.html.erb
app/views/syllabuses/update.html.erb

quedaron controladores de silabuses

Controlersyviews orel

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_navbar.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Chewis home

---

app/controllers/comments_controller.rb
app/controllers/libraries_controller.rb
app/models/syllabus.rb
app/views/comments/edit.html.erb
app/views/comments/index.html.erb
app/views/libraries/index.html.erb
app/views/pages/home.html.erb
app/views/syllabuses/show.html.erb
config/routes.rb

corrrecciones del back

---

Gemfile
Gemfile.lock
app/models/syllabus.rb
app/views/comments/show.html.erb

gema cloudinary

---

app/views/comments/index.html.erb

Se hizo la vista de comentarios con los iconos de fontawesome.com revisar please :)

vista comentarios

---

app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Se puso al español los inicios de sesión :)

iniciar y cerrar sesion sandy vista español

---

app/views/comments/index.html.erb
app/views/syllabuses/index.html.erb
app/views/syllabuses/show.html.erb

lo que hicimos con el maestro Andres - hotwire

Hotwire de viste show de syllabuses

---

app/controllers/syllabuses_controller.rb
app/views/libraries/index.html.erb
app/views/syllabuses/show.html.erb
config/environments/development.rb
config/storage.yml

lo que hicimos con enrique, problema de imagen y de d-flex y la biblioteca

Mi biblioteca carla

---

app/views/comments/index.html.erb
app/views/syllabuses/show.html.erb
app/views/syllabuses_modules/new.html.erb

Hola se hizo bonita la vista Syllabus y Comments

vista show Syllabus y comments

---

app/views/syllabuses/show.html.erb

cambie las dimensiones de la foto de el show de syllabus

dimensiones de la imagen

---

app/controllers/syllabuses_controller.rb
app/controllers/tasks_controller.rb
app/javascript/controllers/application.js
app/javascript/controllers/hello_controller.js
app/models/achievement.rb
app/models/user.rb
app/models/user_point.rb
app/views/layouts/application.html.erb
app/views/syllabuses/show.html.erb
config/routes.rb
db/migrate/20241215225808_create_user_points.rb
db/migrate/20241215225843_create_achievements.rb
db/schema.rb
test/controllers/tasks_controller_test.rb
test/models/achievement_test.rb
test/models/user_point_test.rb

se agregó barra de progreso, pero falta que no sea necesario refrescar esta vista para que marque el avance

Gamificacion or

---

app/assets/stylesheets/pages/_home.scss
app/controllers/comments_controller.rb
app/views/comments/_comment.html.erb
app/views/comments/create.turbo_stream.erb
app/views/comments/edit.html.erb
app/views/comments/index.html.erb

Se realiza partial de comentarios y el turbo stream

---

app/views/syllabuses/show.html.erb

se corrigió la barra de progreso, ya se muestra arriba de los modulos, falta que se guarde el progreso del usuario

ya quedo la barra de progreso con comentarios

---

app/controllers/reviews_controller.rb
app/controllers/syllabuses_controller.rb
app/javascript/controllers/form_submit_controller.js
app/javascript/controllers/star_rating_controller.js
app/models/review.rb
app/models/syllabus.rb
app/views/layouts/application.html.erb
app/views/reviews/new.html.erb
app/views/syllabuses/index.html.erb
app/views/syllabuses/show.html.erb
config/importmap.rb
config/routes.rb
db/migrate/20241217185006_create_reviews.rb
db/migrate/20241217205724_add_syllabus_to_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb
vendor/javascript/star-rating.js.js

Se implementó el raiting y se hizo una nueva migracion de reviews :)

implementacion de rating

---

app/views/syllabuses/show.html.erb

Revisar please raiting mejorado

Se instaló el rating con las estrellitas

---

app/views/syllabuses/show.html.erb

Sandy rama

---

app/assets/stylesheets/pages/_biblioteca.scss
app/views/pages/home.html.erb
app/views/syllabuses/show.html.erb

Chewis new

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_navbar.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/pages_controller.rb
app/controllers/users_controller.rb
app/javascript/application.js
app/models/library.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/pages/my_profile.html.erb
app/views/shared/_navbar.html.erb
app/views/users/destroy.html.erb
config/routes.rb
db/schema.rb
db/seeds.rb
test/controllers/users_controller_test.rb

quedaron las actualizaciones del user

Perfildelusuario orel
